-- AlterTable: 業績データ用フィールドを追加
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "latestRevenue" DECIMAL(18, 0);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "latestNetIncome" DECIMAL(18, 0);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "revenueGrowth" DECIMAL(8, 2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "netIncomeGrowth" DECIMAL(8, 2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "isProfitable" BOOLEAN;
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "profitTrend" TEXT;
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "earningsUpdatedAt" TIMESTAMP(3);
