-- AlterTable
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "latestOpen" DECIMAL(12, 2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "gapUpRate" DECIMAL(8, 2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "volumeSpikeRate" DECIMAL(8, 2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "turnoverValue" DECIMAL(16, 0);
