-- AlterTable: 財務指標カラムを追加
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "pbr" DECIMAL(8,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "per" DECIMAL(8,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "roe" DECIMAL(8,4);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "operatingCF" DECIMAL(15,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "freeCF" DECIMAL(15,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "currentPrice" DECIMAL(12,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "fiftyTwoWeekHigh" DECIMAL(12,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "fiftyTwoWeekLow" DECIMAL(12,2);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "financialDataUpdatedAt" TIMESTAMP(3);
